### ISSUE TITLE
[Feature Request]: 1.20.1 version

### ISSUE THREAD

**Issue by ffernn-dev** [FamroFexl/Circumnavigate#31] opened 2024-11-24 05:28 UTC
### Suggestion

Hey there, I was wondering if there's any chance you could make a build for 1.20.1 (as long as that version isn't missing any features you need)? I'd love to have a play around with this mod.
Thanks, have a good day :)

**Comment by FamroFexl** [comment] 2024-11-24 07:15
Duplicate of #5

**Closed as completed by FamroFexl** 2024-11-24 07:15 UTC
Labels: enhancement
