### ISSUE TITLE
[Feature Request]:1.20.1

### ISSUE THREAD

**Issue by VitaminJake** [FamroFexl/Circumnavigate#5] opened 2024-10-06 01:33 UTC
### Suggestion

This mod is incredible. I've been looking for precisely this feature in Minecraft since the game came out. I have a server that _must_ run 1.20.1 due to other mods - please, I would be extremely indebted if you could make this compatible with that version. I'd be willing to pay you well for your time.

**Comment by Kanyahh** [comment] 2024-10-06 02:18
if your going to 1.20.1 will you be able to make it forge compat on fabric i know there are a few fabric mods able to be used with forge

**Comment by FamroFexl** [comment] 2024-10-06 04:44
@VitaminJake 
1. This mod is still in a very early alpha, so many features don't work, such as the ones addressed in the README. The mod is also prone to instability and crashes due to unforeseen issues. The liability of having my mod be the cause of server crashes, instability, and weird behavior would be detrimental both to the reputation of your server and to my mod.
2. I would be wary of supporting another version while the mod is still in quickly changing states of development. This would require much brainpower towards version management which I would rather devote to feature updates.
3. This mod is what I call a **Massive Modification Mod (M3)** where the changes to the minecraft code are vast and overwhelming, likely making it incompatible with most other mods of the sort. Basically, any point in the code where coordinates are created, provided, or used may be the target of modifications, and therefore mod incompatibilities. My main issue of providing support for your 1.20.1 version is that I would also have to provide compatibility to all of your server mods as well. The back-port to 1.20.1 might also be quite complicated, as it requires dealing with protocol changes introduced in [1.20.2](https://minecraft.wiki/w/Java_Edition_1.20.2#General_2)
4. I don't have much time to work on the mod at the moment, so development will be slow.

Due to these reasons, I would be uncomfortable accepting compensation when I am unsure I would be able to meet your expectations, both now and in the future. <ins>However, a list of mods you are using would inform me to the difficulty of this task, and better inform me how to proceed.</ins>

**Comment by FamroFexl** [comment] 2024-10-06 04:50
@Kanyahh 
> @VitaminJake 
>     3. This mod is what I call a **Massive Modification Mod (M3)** where the changes to the minecraft code are vast and overwhelming, likely making it incompatible with most other mods of the sort.

The forge ecosystem is generally known for its broad inter-mod compatibility provided by its extensive API. This mod needs to completely disregard that objective in order to accomplish its goals, which require vast game-breaking changes. Fabric incompatibility is already a major issue of concern, and I don't think the forge community would benefit from having the additional burden of this mod on their mod developer's shoulders. Unless forge mod developers are willing to make their mods compatible with mine, or participate in the development of my mod to provide compatibility, I cannot see a sustainable path forward with that mod loader.

**Comment by VitaminJake** [comment] 2024-10-06 16:18
I really appreciate the time you took to respond and how detailed your answer is. I also understand how early in development this is and realize that it is massive in scope. Even so, it is such a huge piece of news for me - I always wanted Minecraft to be like this. As such, even with your limitations, I would still be interested in paying you for your time on this project. If you can only work an hour a week or something that's perfect, that means I could pay you by the hour XD. Also, I'd be willing to help in any other way. Testing, writing notes, looking for bugs, playing with configs... I don't know a lot about modding, but if there are mundane tasks I could do or if you wanted to teach me what to look for, I'd love to help in any small capacity.

As for my mod list, it's really, really long and I'm not going to have you working to piece this together with hundreds of other things. There are already some things I'm almost certain would break (fabric waystones, a teleporter mod, comes to mind). Most things like Combat Overhaul and things like Supplementaries would still be fine, I imagine, so the lion's share of mods are probably okay. Regardless, I can do the testing and cut things out to make it work, if the day should come.

**Comment by FamroFexl** [comment] 2024-10-06 21:17
@VitaminJake 

Alright, I'll port it to 1.20.1. It may take me a few weeks to get the multi-version control system set up (see [Stonecutter](https://stonecutter.kikugie.dev/)) and finished with the 1.20.1 port. It would be helpful if you could test new features and report bugs you experience in the realistic production environment of your server.

You can send any compensation you deem acceptable to my [PayPal Business](https://www.paypal.com/paypalme/famrofexl).

**Comment by FamroFexl** [comment] 2024-10-08 23:09
> @VitaminJake
> 
> Alright, I'll see what I can do. It may take me a few weeks to get the multi-version control system set up. It would be helpful if you could test new features and report bugs you experience in the realistic production environment of your server.
> 
> Do you know the reasons your server can't update to 1.20.4, or at least to 1.20.2? It would be immensely helpful if you could compromise with 1.20.2 support.

Scratch that. 1.20.1 has too many changes (especially to chunk-loading systems which I don't want to figure out again) to be supported. 1.20.1 won't be supported.

**Comment by FamroFexl** [comment] 2024-10-08 23:10
No backporting will be supported for the time being.

**Closed by FamroFexl** 2024-10-08 23:10 UTC
Labels: enhancement

**Comment by ffernn-dev** [comment] 2024-11-24 07:18
Ah gotcha, thanks for the detailed info. I could've sworn I looked through the closed issues but somehow didn't spot this duplicate, sorry about that :P
